inherit_gem:
  gnar-style:
    - rubocop/rubocop_gem.yml

AllCops:
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 120
  Severity: refactor

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/MutableConstant:
  Enabled: false
